##Descargamos una versión concreta de UBUNTU, a través del tag
FROM ubuntu:20.04
MAINTAINER C.F ALPHA OMEGA "info@centroalphayomega.com"

##Actualizamos el sistema
RUN apt-get update

##Instalamos nginx
RUN apt-get install -y nginx

##Adicionamos un directorio a la ubicacion por defecto de nginx
VOLUME /var/www/html/
ARG webpage
ADD $webpage /var/www/html/

##Exponemos el Puerto 80
EXPOSE 80

##Arrancamos NGINX a través de ENTRYPOINT para que no pueda ser 
##modificar en la creación del contenedor

ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]
